version: '3.7'
# TO DO before first execution : docker network create -d bridge --subnet=192.168.0.0/24 otm
networks:
  default:
    external:
      name: otm

services:
  zpehlivan-temp:
    build:
      context: .
      network: host
    image: "xxx/temp-docker-ts:2.3.2"
    dns :
       - xxx
    environment:
      PYTHONPATH: "."

    restart: always