version: '3.7'

networks:
  default:
    external:
      name: otm

services:
  zpehlivan-temp:
    build:
      context: ..
      network: host
    image: "xxx/temp-docker-ts:2.3.2"
    dns :
       - xxx
    environment:
      PYTHONPATH: "."

    restart: always